# Basic
title: Mg
subtitle: Website
description: Welcome to my website~
# 头像里面的标题
avatarTitle: wmg_1001
# 头像里面的描述
avatarDesc: Algorithms / Python / C++
url: "http://XJTUmg.me"

# Comment
comment:
    disqus: XJTUmg
    # duoshuo: XJTUmg

# Social
social:
    QQ: 2636609817
    github: XJTUmg
    # twitter:
    mail: wmg_1007@163.com

permalink: /:year/:month/:title/
# Format
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: Blog

# Navigation buttons in the front page.s
nav:
    - {title: Articles, description: archive, url: '/archive'}
    - {title: Tags, description: tags, url: '/tags'}
    - {title: About Me, description: about, url: '/about'}


# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"
